### ISSUE TITLE
Generate also standalone JSON Schema

### ISSUE THREAD

**Issue by jirutka** [dahag-ag/keycloak-openapi#2]
Can you please also generate a JSON with just the JSON Schema?

**Comment by DAHAG-ArisNourbakhsh** [comment]
I don't quite understand, could you elaborate a few points? The OpenAPI json is an "extended subset" of JSON Schema as far as I understand with some keywords that are the same between them, some unique to OpenAPI and vice versa. But both serve different goals and are mildly incompatible because of that.

Is this a request to create plain JSON Schema definitions of just the models (aka the "Components" in OpenApi) ?

If yes, would using something like this [OpenAPI->JSON Schema converter](https://github.com/openapi-contrib/openapi-schema-to-json-schema) on the already existing OpenAPI definitions here yield what you need or would it be missing some JSON Schema unique properties that you require?

If that also doesn't solve your issue, then I'd need to know which keywords of a potential JSON Schema definition you'd need filled out and then I can try looking how to fit that in.

**Comment by jirutka** [comment]
> Is this a request to create plain JSON Schema definitions of just the models (aka the "Components" in OpenApi) ?

Yes, exactly this.

> If yes, would using something like this OpenAPI->JSON Schema converter on the already existing OpenAPI definitions here yield what you need

This works for me, thanks!

However, it would be great if they were provided directly in this repository; otherwise, I would have to maintain a separate project just for this.

**Comment by DAHAG-ArisNourbakhsh** [comment]
Could you try doing the conversion and telling me if the result looks correct to you? If yes then I'll add the conversion as some automated github action step in here or something

**Comment by jirutka** [comment]
I already did it, using the following script:

```js
#!/usr/bin/env node

const FS = require('node:fs')
const { openapiSchemaToJsonSchema: toJsonSchema } = require('@openapi-contrib/openapi-schema-to-json-schema')

const topLevelType = 'RealmRepresentation'


function main (argv) {
  const inputFile = FS.readFileSync(argv[0], 'utf8')

  const oApiSchema = JSON.parse(inputFile, (key, val) => {
    return key === '$ref'
      ? val.replace('#/components/schemas/', '#/$defs/')
      : val
  })

  let schemaUri
  const defs = Object.entries(oApiSchema.components.schemas).reduce((acc, [id, schema]) => {
    const jsonSchema = toJsonSchema(schema)

    // It's the same for all, so just save the last one.
    schemaUri = jsonSchema['$schema']
    delete jsonSchema['$schema']

    acc[id] = jsonSchema
    return acc
  }, {})

  const bundle = {
    '$schema': schemaUri,
    ...defs[topLevelType],
    '$defs': defs,
  }
  delete bundle['$defs'][topLevelType]

  console.log(JSON.stringify(bundle, null, 2))
}

main(process.argv.slice(2))
```

**package.json:**
```json
{
  "dependencies": {
    "@openapi-contrib/openapi-schema-to-json-schema": "^4.0.5"
  }
}
```

```sh
node ./convert.js OpenApiDefinitions/keycloak-21.0.0.json
```

I’ve already validated multiple realm exports against this scheme.

**Comment by DAHAG-ArisNourbakhsh** [comment]
Neat, I'll work on this sometime next week then

**Comment by jirutka** [comment]
I’ve created a project that provides JSON schemas for Keycloak (converted from your OpenAPI definitions): [jirutka/keycloak-json-schema](https://github.com/jirutka/keycloak-json-schema/).
