### ISSUE TITLE
Response types in 23.0.0 are incorrect.

### ISSUE THREAD

**Issue by Fireblade954** [dahag-ag/keycloak-openapi#8]
In the new 23.0.0 file response are defined like "200", but in the previous versions it was like "2xx" i ran into the first issue when creating a realm which returned a 201. Which now fails in the created client as it only accepts 200 request as result.

**Comment by DAHAG-ArisNourbakhsh** [comment]
Thank you for finding that.

I tried generating the openapi definition for the recently released 23.0.1 but it's still a 200 for that particular request. Since the openapi definition is now 100% generated by keycloak itself, it would be prudent to create an issue in their repo as it's out of my control now
